### ISSUE TITLE
please remove "socks5://"

### ISSUE THREAD

**Issue by unfairDude** [x404xx/Asy-Proxier#1]
Could you please remove the specified proxy type at the beginning of any proxy?
this way the output file is already compatible with other tools
the socks type is already specified in the name of the file so its really not needed

thanks for the tool tho

**Comment by x404xx** [comment]
> Could you please remove the specified proxy type at the beginning of any proxy? this way the output file is already compatible with other tools the socks type is already specified in the name of the file so its really not needed
> 
> thanks for the tool tho

However, if you intend to use it, you need to set the proxy type. This is why I designed it that way: simply open the live proxy text file, and you can use it right away in `requests` or `httpx` library, eliminating the need for you to manually set it.

But its ok, I updated the code by adding a saving mode option, so you can use the following command if you want to save the proxy without the proxy type:

> python main.py -pc SOCKS4 -wpt

Check out this page for REQUESTS library: 
How to use [SOCKS](https://docs.python-requests.org/en/latest/user/advanced/#socks)
how to use [HTTP/HTTPS](https://docs.python-requests.org/en/latest/user/advanced/#proxies)

Check out this page for HTTPX library:
How to use [PROXIES](https://www.python-httpx.org/advanced/proxies/)
