### ISSUE TITLE
Please Add Multithreading

### ISSUE THREAD

**Issue by burnmine** [x404xx/Asy-Proxier#2]
Hello

can you please add multithreading feature, is great for this script

thanks

**Comment by x404xx** [comment]
> Hello
> 
> 
> 
> can you please add multithreading feature, is great for this script
> 
> 
> 
> thanks

We appreciate your interest; however, this script already uses asyncio, which is faster than multithreading. 

You may view the log here. how fast it checking:
https://github.com/x404xx/Asy-Proxier/blob/main/runtime.log
